### ISSUE TITLE
personen data service aanpassen voor aanroepen multi personen gezag aanroep

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/personen-data-service#6]

**Comment by nielskorporaal** [comment]
- [ ] code van haal-centraal repo overzetten naar PersonenDataService
- [ ] .templatesyncignore overnemen van personen-informatie-service

**Comment by nielskorporaal** [comment]
In sommige gevallen worden er bij het uitvoeren van `RaadpleegMetBurgerservicenummer ` geen personen gevonden en ontbreekt deze in de response. Een voorbeeld hiervan is [features/persoon/adressering/in-onderzoek:18](https://github.com/BRP-API/personen-data-service/blob/main/features/persoon/adressering/in-onderzoek.feature).
